// Generated by 'peg2'
// https://pub.dev/packages/peg2

void main() {
  final parser = ExampleParser();
  final result = parser.parse(_text);
  if (parser.error != null) {
    throw parser.error;
  }

  print(result);
}

final _text = '''
{"rocket": "🚀 flies to the stars"}
''';

class ExampleParser {
  static const _eof = 0x110000;

  FormatException error;

  int _c;

  int _error;

  List<String> _expected;

  int _failure;

  List<int> _input;

  List<bool> _memoizable;

  List<List<_Memo>> _memos;

  var _mresult;

  int _pos;

  bool _predicate;

  dynamic _result;

  bool _success;

  String _text;

  List<int> _trackCid;

  List<int> _trackPos;

  dynamic parse(String text) {
    if (text == null) {
      throw ArgumentError.notNull('text');
    }
    _text = text;
    _input = _toRunes(text);
    _reset();
    final result = _e0(0, true);
    _buildError();
    _expected = null;
    _input = null;
    return result;
  }

  void _buildError() {
    if (_success) {
      error = null;
      return;
    }

    String escape(int c) {
      switch (c) {
        case 10:
          return r'\n';
        case 13:
          return r'\r';
        case 09:
          return r'\t';
        case _eof:
          return 'end of file';
      }
      return String.fromCharCode(c);
    }

    String getc(int position) {
      if (position < _text.length) {
        return "'${escape(_input[position])}'";
      }
      return 'end of file';
    }

    String report(String message, String source, int start) {
      if (start < 0 || start > source.length) {
        start = null;
      }

      final sb = StringBuffer();
      sb.write(message);
      var line = 0;
      var col = 0;
      var lineStart = 0;
      var started = false;
      if (start != null) {
        for (var i = 0; i < source.length; i++) {
          final c = source.codeUnitAt(i);
          if (!started) {
            started = true;
            lineStart = i;
            line++;
            col = 1;
          } else {
            col++;
          }
          if (c == 10) {
            started = false;
          }
          if (start == i) {
            break;
          }
        }
      }

      if (start == null) {
        sb.writeln('.');
      } else if (line == 0 || start == source.length) {
        sb.write(' (at offset ');
        sb.write(start);
        sb.writeln('):');
      } else {
        sb.write(' (at line ');
        sb.write(line);
        sb.write(', column ');
        sb.write(col);
        sb.writeln('):');
      }

      List<int> escape(int c) {
        switch (c) {
          case 9:
            return [92, 116];
          case 10:
            return [92, 110];
          case 13:
            return [92, 114];
          default:
            return [c];
        }
      }

      const max = 70;
      if (start != null) {
        final c1 = <int>[];
        final c2 = <int>[];
        final half = max ~/ 2;
        var cr = false;
        for (var i = start; i >= lineStart && c1.length < half; i--) {
          if (i == source.length) {
            c2.insert(0, 94);
          } else {
            final c = source.codeUnitAt(i);
            final escaped = escape(c);
            c1.insertAll(0, escaped);
            if (c == 10) {
              cr = true;
            }

            final r = i == start ? 94 : 32;
            for (var k = 0; k < escaped.length; k++) {
              c2.insert(0, r);
            }
          }
        }

        for (var i = start + 1;
            i < source.length && c1.length < max && !cr;
            i++) {
          final c = source.codeUnitAt(i);
          final escaped = escape(c);
          c1.addAll(escaped);
          if (c == 10) {
            break;
          }
        }

        final text1 = String.fromCharCodes(c1);
        final text2 = String.fromCharCodes(c2);
        sb.writeln(text1);
        sb.writeln(text2);
      }

      return sb.toString();
    }

    final temp = _expected.toList();
    temp.sort((e1, e2) => e1.compareTo(e2));
    final expected = temp.toSet();
    final hasMalformed = false;
    if (expected.isNotEmpty) {
      if (!hasMalformed) {
        final sb = StringBuffer();
        sb.write('Expected ');
        sb.write(expected.join(', '));
        sb.write(' but found ');
        sb.write(getc(_error));
        final title = sb.toString();
        final message = report(title, _text, _error);
        error = FormatException(message);
      } else {
        final reason = _error == _text.length ? 'Unterminated' : 'Malformed';
        final sb = StringBuffer();
        sb.write(reason);
        sb.write(' ');
        sb.write(expected.join(', '));
        final title = sb.toString();
        final message = report(title, _text, _error);
        error = FormatException(message);
      }
    } else {
      final sb = StringBuffer();
      sb.write('Unexpected character ');
      sb.write(getc(_error));
      final title = sb.toString();
      final message = report(title, _text, _error);
      error = FormatException(message);
    }
  }

  void _fail(List<String> expected) {
    if (_error < _failure) {
      _error = _failure;
      _expected = [];
    }
    if (_error == _failure) {
      _expected.addAll(expected);
    }
  }

  int _matchRanges(List<int> ranges) {
    int result;
    _success = false;
    for (var i = 0; i < ranges.length; i += 2) {
      if (ranges[i] <= _c) {
        if (ranges[i + 1] >= _c) {
          result = _c;
          _c = _input[_pos += _c <= 0xffff ? 1 : 2];
          _success = true;
          break;
        }
      } else {
        break;
      }
    }

    if (!_success) {
      _failure = _pos;
    }

    return result;
  }

  String _matchString(String text) {
    String result;
    final length = text.length;
    final rest = _text.length - _pos;
    final count = length > rest ? rest : length;
    var pos = _pos;
    var i = 0;
    for (; i < count; i++, pos++) {
      if (text.codeUnitAt(i) != _text.codeUnitAt(pos)) {
        break;
      }
    }

    if (_success = i == length) {
      _c = _input[_pos += length];
      result = text;
    } else {
      _failure = _pos + i;
    }

    return result;
  }

  bool _memoized(int id, int cid) {
    final memos = _memos[_pos];
    if (memos != null) {
      for (var i = 0; i < memos.length; i++) {
        final memo = memos[i];
        if (memo.id == id) {
          _pos = memo.pos;
          _mresult = memo.result;
          _success = memo.success;
          _c = _input[_pos];
          return true;
        }
      }
    }

    if (_memoizable[cid] != null) {
      return false;
    }

    final lastCid = _trackCid[id];
    final lastPos = _trackPos[id];
    _trackCid[id] = cid;
    _trackPos[id] = _pos;
    if (lastCid == null) {
      return false;
    }

    if (lastPos == _pos) {
      if (lastCid != cid) {
        _memoizable[lastCid] = true;
        _memoizable[cid] = false;
      }
    }

    return false;
  }

  void _memoize(int id, int pos, result) {
    var memos = _memos[pos];
    if (memos == null) {
      memos = [];
      _memos[pos] = memos;
    }

    final memo = _Memo(
      id: id,
      pos: _pos,
      result: result,
      success: _success,
    );

    memos.add(memo);
  }

  void _reset() {
    _c = _input[0];
    _error = 0;
    _expected = [];
    _failure = -1;
    _memoizable = [];
    _memoizable.length = 183;
    _memos = [];
    _memos.length = _input.length + 1;
    _pos = 0;
    _predicate = false;
    _success = false;
    _trackCid = [];
    _trackCid.length = 183;
    _trackPos = [];
    _trackPos.length = 183;
  }

  List<int> _toRunes(String source) {
    final length = source.length;
    final result = List<int>(length + 1);
    for (var pos = 0; pos < length;) {
      int c;
      final start = pos;
      final leading = source.codeUnitAt(pos++);
      if ((leading & 0xFC00) == 0xD800 && pos < length) {
        final trailing = source.codeUnitAt(pos);
        if ((trailing & 0xFC00) == 0xDC00) {
          c = 0x10000 + ((leading & 0x3FF) << 10) + (trailing & 0x3FF);
          pos++;
        } else {
          c = leading;
        }
      } else {
        c = leading;
      }

      result[start] = c;
    }

    result[length] = 0x110000;
    return result;
  }

  dynamic _e0(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    dynamic $04;
    for (;;) {
      if ($02 >= 0 && $02 <= 1114111) {
        int $05;
        if (_c >= 9 && _c <= 10 || _c == 13 || _c == 32) {
          _success = true;
          $05 = _c;
          _c = _input[++_pos];
        } else {
          _success = false;
          _failure = _pos;
        }
        if (_success) {
          List<int> $06;
          if ($01) {}
          for (;;) {
            int $07;
            if (_c >= 9 && _c <= 10 || _c == 13 || _c == 32) {
              _success = true;
              $07 = _c;
              _c = _input[++_pos];
            } else {
              _success = false;
              _failure = _pos;
            }
            if (!_success) {
              break;
            }
            $06.add($07);
          }
          if (_success) {
            final $08 = _e180();
            if (_success) {
              List<int> $09 = $08;
              if (_success) {
                final $010 = _e63();
                if (_success) {
                  List<int> $011 = $010;
                  if (_success) {
                    List<int> $012 = $011;
                    if (_success) {
                      final $013 = _e1();
                      if (_success) {
                        dynamic $014 = $013;
                        if (_success) {
                          $04 = $014;
                          break;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  List<int> _e179(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    List<int> $04;
    for (;;) {
      if ($02 >= 0 && $02 <= 1114111) {
        int $05;
        if (_c >= 9 && _c <= 10 || _c == 13 || _c == 32) {
          _success = true;
          $05 = _c;
          _c = _input[++_pos];
        } else {
          _success = false;
          _failure = _pos;
        }
        if (_success) {
          List<int> $06;
          if ($01) {}
          for (;;) {
            int $07;
            if (_c >= 9 && _c <= 10 || _c == 13 || _c == 32) {
              _success = true;
              $07 = _c;
              _c = _input[++_pos];
            } else {
              _success = false;
              _failure = _pos;
            }
            if (!_success) {
              break;
            }
            $06.add($07);
          }
          if (_success) {
            final $08 = _e180();
            if (_success) {
              List<int> $09 = $08;
              if (_success) {
                $04 = $09;
                break;
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  dynamic _e6(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    dynamic $04;
    for (;;) {
      if ($02 >= 34 && $02 <= 90) {
        int $05;
        if (_c == 45) {
          _success = true;
          $05 = _c;
          _c = _input[++_pos];
        } else {
          _success = false;
          _failure = _pos;
        }
        if (_success) {
          int $06 = $05;
          if (_success) {
            final $07 = _e84();
            if (_success) {
              int $08 = $07;
              if (_success) {
                final $09 = _text.substring($03, _pos);
                if (_success) {
                  final $010 = _e81();
                  if (_success) {
                    num $011 = $010;
                    if (_success) {
                      final $012 = _e17();
                      if (_success) {
                        dynamic $013 = $012;
                        if (_success) {
                          $04 = $013;
                          break;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
        final $014 = '\"';
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $015 = _e74();
          if (_success) {
            String $016 = $015;
            if (_success) {
              final $017 = _e19();
              if (_success) {
                dynamic $018 = $017;
                if (_success) {
                  $04 = $018;
                  break;
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 91) {
        final $019 = '[';
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $020 = _e118();
          if (_success) {
            String $021 = $020;
            if (_success) {
              final $022 = _e22();
              if (_success) {
                List $023 = $022;
                if (_success) {
                  final $024 = _e7();
                  if (_success) {
                    dynamic $025 = $024;
                    if (_success) {
                      $04 = $025;
                      break;
                    }
                  }
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
        int $026;
        if (_c == 45) {
          _success = true;
          $026 = _c;
          _c = _input[++_pos];
        } else {
          _success = false;
          _failure = _pos;
        }
        if (_success) {
          int $027 = $026;
          if (_success) {
            final $028 = _e84();
            if (_success) {
              int $029 = $028;
              if (_success) {
                final $030 = _text.substring($03, _pos);
                if (_success) {
                  final $031 = _e81();
                  if (_success) {
                    num $032 = $031;
                    if (_success) {
                      final $033 = _e17();
                      if (_success) {
                        dynamic $034 = $033;
                        if (_success) {
                          $04 = $034;
                          break;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 >= 92 && $02 <= 101 ||
          $02 >= 103 && $02 <= 109 ||
          $02 >= 111 && $02 <= 115 ||
          $02 >= 117 && $02 <= 122 ||
          $02 >= 124 && $02 <= 1114111) {
        int $035;
        if (_c == 45) {
          _success = true;
          $035 = _c;
          _c = _input[++_pos];
        } else {
          _success = false;
          _failure = _pos;
        }
        if (_success) {
          int $036 = $035;
          if (_success) {
            final $037 = _e84();
            if (_success) {
              int $038 = $037;
              if (_success) {
                final $039 = _text.substring($03, _pos);
                if (_success) {
                  final $040 = _e81();
                  if (_success) {
                    num $041 = $040;
                    if (_success) {
                      final $042 = _e17();
                      if (_success) {
                        dynamic $043 = $042;
                        if (_success) {
                          $04 = $043;
                          break;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 102) {
        final $044 = _matchString('false');
        if (_success) {
          final $045 = _e59();
          if (_success) {
            dynamic $046 = $045;
            if (_success) {
              final $047 = _e9();
              if (_success) {
                dynamic $048 = $047;
                if (_success) {
                  $04 = $048;
                  break;
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
        int $049;
        if (_c == 45) {
          _success = true;
          $049 = _c;
          _c = _input[++_pos];
        } else {
          _success = false;
          _failure = _pos;
        }
        if (_success) {
          int $050 = $049;
          if (_success) {
            final $051 = _e84();
            if (_success) {
              int $052 = $051;
              if (_success) {
                final $053 = _text.substring($03, _pos);
                if (_success) {
                  final $054 = _e81();
                  if (_success) {
                    num $055 = $054;
                    if (_success) {
                      final $056 = _e17();
                      if (_success) {
                        dynamic $057 = $056;
                        if (_success) {
                          $04 = $057;
                          break;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 110) {
        final $058 = _matchString('null');
        if (_success) {
          final $059 = _e66();
          if (_success) {
            dynamic $060 = $059;
            if (_success) {
              final $061 = _e11();
              if (_success) {
                dynamic $062 = $061;
                if (_success) {
                  $04 = $062;
                  break;
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
        int $063;
        if (_c == 45) {
          _success = true;
          $063 = _c;
          _c = _input[++_pos];
        } else {
          _success = false;
          _failure = _pos;
        }
        if (_success) {
          int $064 = $063;
          if (_success) {
            final $065 = _e84();
            if (_success) {
              int $066 = $065;
              if (_success) {
                final $067 = _text.substring($03, _pos);
                if (_success) {
                  final $068 = _e81();
                  if (_success) {
                    num $069 = $068;
                    if (_success) {
                      final $070 = _e17();
                      if (_success) {
                        dynamic $071 = $070;
                        if (_success) {
                          $04 = $071;
                          break;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 116) {
        final $072 = _matchString('true');
        if (_success) {
          final $073 = _e70();
          if (_success) {
            dynamic $074 = $073;
            if (_success) {
              final $075 = _e13();
              if (_success) {
                dynamic $076 = $075;
                if (_success) {
                  $04 = $076;
                  break;
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
        int $077;
        if (_c == 45) {
          _success = true;
          $077 = _c;
          _c = _input[++_pos];
        } else {
          _success = false;
          _failure = _pos;
        }
        if (_success) {
          int $078 = $077;
          if (_success) {
            final $079 = _e84();
            if (_success) {
              int $080 = $079;
              if (_success) {
                final $081 = _text.substring($03, _pos);
                if (_success) {
                  final $082 = _e81();
                  if (_success) {
                    num $083 = $082;
                    if (_success) {
                      final $084 = _e17();
                      if (_success) {
                        dynamic $085 = $084;
                        if (_success) {
                          $04 = $085;
                          break;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 123) {
        final $086 = '{';
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $087 = _e110();
          if (_success) {
            String $088 = $087;
            if (_success) {
              final $089 = _e36();
              if (_success) {
                Map<String, dynamic> $090 = $089;
                if (_success) {
                  final $091 = _e15();
                  if (_success) {
                    dynamic $092 = $091;
                    if (_success) {
                      $04 = $092;
                      break;
                    }
                  }
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
        int $093;
        if (_c == 45) {
          _success = true;
          $093 = _c;
          _c = _input[++_pos];
        } else {
          _success = false;
          _failure = _pos;
        }
        if (_success) {
          int $094 = $093;
          if (_success) {
            final $095 = _e84();
            if (_success) {
              int $096 = $095;
              if (_success) {
                final $097 = _text.substring($03, _pos);
                if (_success) {
                  final $098 = _e81();
                  if (_success) {
                    num $099 = $098;
                    if (_success) {
                      final $0100 = _e17();
                      if (_success) {
                        dynamic $0101 = $0100;
                        if (_success) {
                          $04 = $0101;
                          break;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  dynamic _e54(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    dynamic $04;
    for (;;) {
      if ($02 >= 0 && $02 <= 1114111) {
        int $05;
        if (_c >= 0 && _c <= 1114111) {
          _success = true;
          $05 = _c;
          _c = _input[_pos += _c <= 65535 ? 1 : 2];
        } else {
          _success = false;
          _failure = _pos;
        }
        if (_success) {
          _success = false;
          final $06 = null;
          if (_success) {
            final $07 = _e55();
            if (_success) {
              dynamic $08 = $07;
              if (_success) {
                $04 = $08;
                break;
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  num _e80(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    num $04;
    for (;;) {
      if ($02 >= 0 && $02 <= 1114111) {
        int $05;
        if (_c == 45) {
          _success = true;
          $05 = _c;
          _c = _input[++_pos];
        } else {
          _success = false;
          _failure = _pos;
        }
        if (_success) {
          int $06 = $05;
          if (_success) {
            final $07 = _e84();
            if (_success) {
              int $08 = $07;
              if (_success) {
                final $09 = _text.substring($03, _pos);
                if (_success) {
                  final $010 = _e81();
                  if (_success) {
                    num $011 = $010;
                    if (_success) {
                      $04 = $011;
                      break;
                    }
                  }
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  int _e133(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    int $04;
    for (;;) {
      if ($02 >= 32 && $02 <= 33 ||
          $02 >= 35 && $02 <= 91 ||
          $02 >= 93 && $02 <= 1114111) {
        final $05 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e173();
          if (_success) {
            int $07 = $06;
            if (_success) {
              final $08 = _e137();
              if (_success) {
                int $09 = $08;
                if (_success) {
                  $04 = $09;
                  break;
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 92) {
        final $010 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $011 = _e134();
          if (_success) {
            int $012 = $011;
            if (_success) {
              $04 = $012;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  String _e73(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    String $04;
    for (;;) {
      if ($02 == 34) {
        final $05 = '\"';
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e74();
          if (_success) {
            String $07 = $06;
            if (_success) {
              $04 = $07;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  String _e117(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    String $04;
    for (;;) {
      if ($02 == 91) {
        final $05 = '[';
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e118();
          if (_success) {
            String $07 = $06;
            if (_success) {
              $04 = $07;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  String _e121(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    String $04;
    for (;;) {
      if ($02 == 93) {
        final $05 = ']';
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e122();
          if (_success) {
            String $07 = $06;
            if (_success) {
              $04 = $07;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  List _e21(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    List $04;
    for (;;) {
      if ($02 == 91) {
        final $05 = '[';
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e118();
          if (_success) {
            String $07 = $06;
            if (_success) {
              final $08 = _e22();
              if (_success) {
                List $09 = $08;
                if (_success) {
                  $04 = $09;
                  break;
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  dynamic _e58(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    dynamic $04;
    for (;;) {
      if ($02 == 102) {
        final $05 = _matchString('false');
        if (_success) {
          final $06 = _e59();
          if (_success) {
            dynamic $07 = $06;
            if (_success) {
              $04 = $07;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  dynamic _e65(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    dynamic $04;
    for (;;) {
      if ($02 == 110) {
        final $05 = _matchString('null');
        if (_success) {
          final $06 = _e66();
          if (_success) {
            dynamic $07 = $06;
            if (_success) {
              $04 = $07;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  dynamic _e69(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    dynamic $04;
    for (;;) {
      if ($02 == 116) {
        final $05 = _matchString('true');
        if (_success) {
          final $06 = _e70();
          if (_success) {
            dynamic $07 = $06;
            if (_success) {
              $04 = $07;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  String _e109(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    String $04;
    for (;;) {
      if ($02 == 123) {
        final $05 = '{';
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e110();
          if (_success) {
            String $07 = $06;
            if (_success) {
              $04 = $07;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  String _e113(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    String $04;
    for (;;) {
      if ($02 == 125) {
        final $05 = '}';
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e114();
          if (_success) {
            String $07 = $06;
            if (_success) {
              $04 = $07;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  Map<String, dynamic> _e35(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    Map<String, dynamic> $04;
    for (;;) {
      if ($02 == 123) {
        final $05 = '{';
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e110();
          if (_success) {
            String $07 = $06;
            if (_success) {
              final $08 = _e36();
              if (_success) {
                Map<String, dynamic> $09 = $08;
                if (_success) {
                  $04 = $09;
                  break;
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  int _e172(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    int $04;
    for (;;) {
      if ($02 >= 32 && $02 <= 33) {
        final $05 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e173();
          if (_success) {
            int $07 = $06;
            if (_success) {
              $04 = $07;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 >= 35 && $02 <= 91) {
        final $08 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $09 = _e175();
          if (_success) {
            int $010 = $09;
            if (_success) {
              $04 = $010;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 >= 93 && $02 <= 1114111) {
        final $011 = _c;
        _success = true;
        _c = _input[_pos += _c <= 65535 ? 1 : 2];
        if (_success) {
          final $012 = _e177();
          if (_success) {
            int $013 = $012;
            if (_success) {
              $04 = $013;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  int _e139(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    int $04;
    for (;;) {
      if ($02 == 34) {
        final $05 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e140();
          if (_success) {
            int $07 = $06;
            if (_success) {
              $04 = $07;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 47) {
        final $08 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $09 = _e144();
          if (_success) {
            int $010 = $09;
            if (_success) {
              $04 = $010;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 92) {
        final $011 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $012 = _e142();
          if (_success) {
            int $013 = $012;
            if (_success) {
              $04 = $013;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 98) {
        final $014 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $015 = _e146();
          if (_success) {
            int $016 = $015;
            if (_success) {
              $04 = $016;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 102) {
        final $017 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $018 = _e148();
          if (_success) {
            int $019 = $018;
            if (_success) {
              $04 = $019;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 110) {
        final $020 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $021 = _e150();
          if (_success) {
            int $022 = $021;
            if (_success) {
              $04 = $022;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 114) {
        final $023 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $024 = _e152();
          if (_success) {
            int $025 = $024;
            if (_success) {
              $04 = $025;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 116) {
        final $026 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $027 = _e154();
          if (_success) {
            int $028 = $027;
            if (_success) {
              $04 = $028;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 == 117) {
        final $029 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $030 = _e156();
          if (_success) {
            int $031 = $030;
            if (_success) {
              $04 = $031;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  int _e159(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    int $04;
    for (;;) {
      if ($02 >= 48 && $02 <= 57 ||
          $02 >= 65 && $02 <= 70 ||
          $02 >= 97 && $02 <= 102) {
        final $05 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e166();
          if (_success) {
            int $07 = $06;
            if (_success) {
              final $08 = _e160();
              if (_success) {
                int $09 = $08;
                if (_success) {
                  $04 = $09;
                  break;
                }
              }
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  int _e165(int $00, bool $01) {
    final $02 = _c;
    final $03 = _pos;
    int $04;
    for (;;) {
      if ($02 >= 48 && $02 <= 57) {
        final $05 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $06 = _e170();
          if (_success) {
            int $07 = $06;
            if (_success) {
              $04 = $07;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 >= 65 && $02 <= 70) {
        final $08 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $09 = _e168();
          if (_success) {
            int $010 = $09;
            if (_success) {
              $04 = $010;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
      if ($02 >= 97 && $02 <= 102) {
        final $011 = _c;
        _success = true;
        _c = _input[++_pos];
        if (_success) {
          final $012 = _e166();
          if (_success) {
            int $013 = $012;
            if (_success) {
              $04 = $013;
              break;
            }
          }
        }
        if (!_success) {
          _c = $02;
          _pos = $03;
        }
      }
    }
    return $04;
    return $04;
  }

  List<int> _e180() {
    List<int> $00;
    List<int> $01;
    for (;;) {
      int $02;
      if (_c >= 9 && _c <= 10 || _c == 13 || _c == 32) {
        _success = true;
        _c = _input[++_pos];
      } else {
        _success = false;
        _failure = _pos;
      }
      if (!_success) {
        break;
      }
      $01.add($02);
    }
    $00 = $01;
  }

  List<int> _e63() {
    List<int> $00;
    final $01 = _e179(64, $01);
    $00 = $01;
  }

  dynamic _e1() {
    dynamic $00;
    List<int> $01 = $012;
    final $02 = _e6(4, $01);
    if (_success) {
      final $03 = _e54(5, $01);
      if (_success) {
        $00 = $02;
      }
    }
  }

  int _e84() {
    int $00;
    int $01 = $06;
    int $02 = $01;
    if (_success) {
      int $03 = $02;
      int $04 = $03;
      $00 = $01;
    }
  }

  num _e81() {
    num $00;
    final $01 = _text.substring($03, _pos);
    if (_success) {
      final $02 = _e179(108, $01);
      if (_success) {
        final n = $01;
        num $$;
        $$ = num.parse(n);
        $00 = $$;
      }
    }
  }

  num _e17() {
    num $00;
    final $01 = _e80(18, $01);
    if (_success) {
      $00 = $01;
    }
  }

  String _e74() {
    String $00;
    final $01 = '\"';
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      List<int> $02;
      if ($01) {}
      for (;;) {
        final $03 = _e133(77, $01);
        if (!_success) {
          break;
        }
        $02.add($03);
      }
      final $04 = '\"';
      _success = true;
      _c = _input[++_pos];
      if (_success) {
        final $05 = _e179(79, $01);
        if (_success) {
          final c = $02;
          String $$;
          $$ = String.fromCharCodes(c);
          $00 = $$;
        }
      }
    }
  }

  String _e19() {
    String $00;
    final $01 = _e73(20, $01);
    if (_success) {
      $00 = $01;
    }
  }

  String _e118() {
    String $00;
    final $01 = '[';
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      final $02 = _e179(120, $01);
      $00 = $01;
    }
  }

  List _e22() {
    List $00;
    final $01 = _e117(23, $01);
    if (_success) {
      List $02 = $01;
      final $03 = _e121(26, $01);
      if (_success) {
        final v = $02;
        List $$;
        $$ = v ?? [];
        $00 = $$;
      }
    }
  }

  List _e7() {
    List $00;
    final $01 = _e21(8, $01);
    if (_success) {
      $00 = $01;
    }
  }

  dynamic _e59() {
    dynamic $00;
    final $01 = _matchString('false');
    if (_success) {
      final $02 = _e179(61, $01);
      if (_success) {
        dynamic $$;
        $$ = false;
        $00 = $$;
      }
    }
  }

  dynamic _e9() {
    dynamic $00;
    final $01 = _e58(10, $01);
    if (_success) {
      $00 = $01;
    }
  }

  dynamic _e66() {
    dynamic $00;
    final $01 = _matchString('null');
    if (_success) {
      final $02 = _e179(68, $01);
      if (_success) {
        dynamic $$;
        $$ = null;
        $00 = $$;
      }
    }
  }

  dynamic _e11() {
    dynamic $00;
    final $01 = _e65(12, $01);
    if (_success) {
      $00 = $01;
    }
  }

  dynamic _e70() {
    dynamic $00;
    final $01 = _matchString('true');
    if (_success) {
      final $02 = _e179(72, $01);
      if (_success) {
        dynamic $$;
        $$ = true;
        $00 = $$;
      }
    }
  }

  dynamic _e13() {
    dynamic $00;
    final $01 = _e69(14, $01);
    if (_success) {
      $00 = $01;
    }
  }

  String _e110() {
    String $00;
    final $01 = '{';
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      final $02 = _e179(112, $01);
      $00 = $01;
    }
  }

  Map<String, dynamic> _e36() {
    Map<String, dynamic> $00;
    final $01 = _e109(37, $01);
    if (_success) {
      List<MapEntry<String, dynamic>> $02 = $01;
      final $03 = _e113(40, $01);
      if (_success) {
        final m = $02;
        Map<String, dynamic> $$;
        $$ = <String, dynamic>{}..addEntries(m ?? []);
        $00 = $$;
      }
    }
  }

  Map<String, dynamic> _e15() {
    Map<String, dynamic> $00;
    final $01 = _e35(16, $01);
    if (_success) {
      $00 = $01;
    }
  }

  dynamic _e55() {
    dynamic $00;
    _success = false;
    final $01 = null;
    if (_success) {
      $00 = $01;
    }
  }

  int _e173() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      $00 = $01;
    }
  }

  int _e137() {
    int $00;
    final $01 = _e172(138, $01);
    if (_success) {
      $00 = $01;
    }
  }

  int _e134() {
    int $00;
    int $01;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      final $02 = _e139(136, $01);
      if (_success) {
        $00 = $02;
      }
    }
  }

  String _e122() {
    String $00;
    final $01 = ']';
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      final $02 = _e179(124, $01);
      $00 = $01;
    }
  }

  String _e114() {
    String $00;
    final $01 = '}';
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      final $02 = _e179(116, $01);
      $00 = $01;
    }
  }

  int _e175() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      $00 = $01;
    }
  }

  int _e177() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[_pos += _c <= 65535 ? 1 : 2];
    if (_success) {
      $00 = $01;
    }
  }

  int _e140() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      $00 = $01;
    }
  }

  int _e144() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      $00 = $01;
    }
  }

  int _e142() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      $00 = $01;
    }
  }

  int _e146() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      int $$;
      $$ = 0x8;
      $00 = $$;
    }
  }

  int _e148() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      int $$;
      $$ = 0xC;
      $00 = $$;
    }
  }

  int _e150() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      int $$;
      $$ = 0xA;
      $00 = $$;
    }
  }

  int _e152() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      int $$;
      $$ = 0xD;
      $00 = $$;
    }
  }

  int _e154() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      int $$;
      $$ = 0x9;
      $00 = $$;
    }
  }

  int _e156() {
    int $00;
    int $01;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      final $02 = _e159(158, $01);
      if (_success) {
        $00 = $02;
      }
    }
  }

  int _e166() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      int $$;
      $$ = $$ - 97;
      $00 = $$;
    }
  }

  int _e160() {
    int $00;
    final $01 = _e165(161, $01);
    if (_success) {
      final $02 = _e165(162, $01);
      if (_success) {
        final $03 = _e165(163, $01);
        if (_success) {
          final $04 = _e165(164, $01);
          if (_success) {
            final a = $01;
            final b = $02;
            final c = $03;
            final d = $04;
            int $$;
            $$ = a * 0xfff + b * 0xff + c * 0xf + d;
            $00 = $$;
          }
        }
      }
    }
  }

  int _e170() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      int $$;
      $$ = $$ - 48;
      $00 = $$;
    }
  }

  int _e168() {
    int $00;
    final $01 = _c;
    _success = true;
    _c = _input[++_pos];
    if (_success) {
      int $$;
      $$ = $$ - 65;
      $00 = $$;
    }
  }
}

class _Memo {
  final int id;

  final int pos;

  final result;

  final bool success;

  _Memo({
    this.id,
    this.pos,
    this.result,
    this.success,
  });
}

// ignore_for_file: unused_element
// ignore_for_file: unused_field
