name: peg2
description: PEG+ (Parsing expression grammar) parser source code generator, command line tool.
homepage: https://github.com/mezoni/peg2
version: 0.1.34
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  args: ^1.6.0   
  dart_style: ^1.3.6
  enumerable: ^0.1.3
  lists: ^0.1.6
  meta: ^1.1.8
  path: ^1.7.0  
  strings: ^0.1.2
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3
