name: peg2
description: PEG+ (Parsing expression grammar) parser source code generator, command line tool.
homepage: https://github.com/mezoni/peg2
version: 0.2.8
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  args: ^2.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0  
  lists: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0  
  strings: ^0.2.1
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
