name: peg2
description: PEG+ (Parsing expression grammar) parser generator.
version: 0.1.0
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  args: ^1.5.1
  dart_style: ^1.3.3
  lists: ^0.1.3
  strings: ^0.1.2
dev_dependencies:  
  path: ^1.6.2
  pedantic: ^1.9.0
  test: ^1.6.3
