name: peg2
description: PEG+ (Parsing expression grammar) parser source code generator, command line tool.
homepage: https://github.com/mezoni/peg2
version: 0.1.33
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  args: ^1.5.1   
  dart_style: ^1.3.3
  enumerable: ^0.1.3
  lists: ^0.1.5
  meta: ^1.1.8
  path: ^1.6.2  
  strings: ^0.1.2
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.3
